### ISSUE TITLE
Doesn't deploy on Cloudflare Pages (needs node v14)

### ISSUE THREAD

**Issue by murraybauer** [lukeed/pages-fullstack#2]
Tried to test this out from the Blog on Cloudflare Pages.

Build fails due to Cloudflare node version being too old.  

Is there anyway to build in own CI and push to CF Pages?

```

> esbuild@0.13.14 postinstall /opt/buildhome/repo/node_modules/esbuild
--
13:25:01.401 | > node install.js
13:25:01.401 |  
13:25:01.546 | npm WARN notsup Unsupported engine for @sveltejs/kit@1.0.0-next.196: wanted: {"node":">=14.13"} (current: {"node":"12.18.0","npm":"6.14.4"})

```

**Comment by lukeed** [comment]
Yes in your Pages project settings, add a `NODE_VERSION` of `14` or `16` to both the preview and production environments. There's an accompanying video walkthrough that includes that instruction.

Also, the output directory is `.svelte-kit/cloudflare` I believe

**Comment by murraybauer** [comment]
Thanks @lukeed.  Beginer to Pages. Those settings worked.
