### ISSUE TITLE
API routes with secrets/server side only environment variables

### ISSUE THREAD

**Issue by charifmews** [lukeed/pages-fullstack#6]
How can you access secrets (runtime not client accessible environment variables) for Sveltekit API endpoints with cloudflare pages? Tested a couple of approaches, but can't figure it out unfortunately.

**Comment by charifmews** [comment]
The only approach that works for me is `import.meta.env.VITE_SOME_SECRET` and it isn't leaked to the client-side app. However it does require a new deployment when you change the environment variable (probably makes sense in hindsight). Will close the issue now and I think there is probably not a way to dynamically change a secret/environment variable, but always need a redeploy. Will close this issue for now.

**Comment by FunMiles** [comment]
I tried your approach and did not get it to work. I get `undefined` as the value of `import.meta.env.VITE_SOME_SECRET`.
I am using sveltekit.
Where dd you define the environment variable?

**Comment by FunMiles** [comment]
PS: Trying to print import.meta.env only has the following variables defined:

> BASE_URL: "/_app/immutable/"
DEV: false
MODE: "production"
PROD: true
VITE_SVELTEKIT_APP_VERSION: "1651234567890"
VITE_SVELTEKIT_APP_VERSION_FILE: "_app/version.json"
VITE_SVELTEKIT_APP_VERSION_POLL_INTERVAL: "0"

**Comment by FunMiles** [comment]
I found the solution.
Making use of the `plaform` property is the way to go, as documented in https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare

Just add a typescript description:
```js
interface Platform {
		env: {
			SOME_SECRET: string;
		};
		context: {
			waitUntil(promise: Promise<any>): void;
		}
	}
```
Then use the parameter in your endpoints:
```js
export const post: RequestHandler = async ({ request, locals, platform }) => {
   const my_secret = platform.env.SOME_SECRET;
   ... // make use of the secret
 }
```
