### ISSUE TITLE
Is there a way to use both `svelte-kit dev` and `wrangler pages dev`?

### ISSUE THREAD

**Issue by lmaccherone** [lukeed/pages-fullstack#7]
I'd love to be able to use both `svelte-kit dev` and `wrangler pages dev`. I've tried

    wrangler pages dev ./.svelte-kit/cloudflare -- svelte-kit dev

but that doesn't proxy the assets or the api correctly.

I'm about to try to launch them separately and sense that the cloudflare services are local, but I thought I'd ask first here in case someone has already figured this out.

**Comment by lukeed** [comment]
Check out the dev branch: https://github.com/lukeed/pages-fullstack/tree/dev

it was the best melded solution I could come up with

**Comment by lmaccherone** [comment]
Cool. Do you just use `npm run dev` or do you first do `npm run watch`, then `npm run dev`?

**Comment by lukeed** [comment]
It’s watch only. Not the same DX as dev but it gets the job done. Use dev for quick development for things like ui/styling and then watch to make sure it actually works lol. It’s kinda rough hence not being main branch

**Comment by lmaccherone** [comment]
I'll give it a try and at least provide feedback. Thanks.

**Comment by lukeed** [comment]
Np, closing as there's not much else that can be done here w/o directly affecting either tool

**Comment by lmaccherone** [comment]
Finally got around to trying this but can't figure out how to expose KV and Durable Object namespaces to my endpoints and test them locally. Any help would be appreciated.

**Comment by colinhowells** [comment]
[That's covered in the `adapter-cloudflare` docs](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare#environment-variables) – I missed this detail myself until just this week so hopefully that’ll help you

**Comment by colinhowells** [comment]
ok, this is [real now](https://github.com/sveltejs/kit/issues/2844#issuecomment-1076408282), and i can confirm it's operational:

```js
/**
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export async function get({ params, platform }) {
	
	let yerData = null;
	let someOtherDataObject = {};
	let KV = null;

	// https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare#environment-variables
	if (platform?.env?.YOUR_KV_NAMESPACE) {
		KV = platform.env.YOUR_KV_NAMESPACE;
		yerData = await KV.get('some_sort_of_key');
	}

	if (yerData) {
		someOtherDataObject = someMagic(yerData);
	}

	if (KV && someOtherDataObject) {
		KV.put('some_other_key_maybe', JSON.stringify(someOtherDataObject), { expirationTtl: 2629746 }); // 1 month expiration
	}

	return {
		body: someOtherDataObject,
	};
}
```
