### ISSUE TITLE
Do you have a wrangler.toml for this project?

### ISSUE THREAD

**Issue by alexbjorlig** [lukeed/pages-fullstack#9]
I'm having isssues deploying with wrangler to cloudflare pages.

**Comment by lukeed** [comment]
You don’t use a wrangler toml file with Pages

**Comment by alexbjorlig** [comment]
ok 😅

**Comment by alexbjorlig** [comment]
But how do you tail logs from the "functions" that are deployed then?

**Comment by lukeed** [comment]
At this time you can only access Pages logs from the dashboard
